apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: debug-gateway-parameters
  namespace: agentgateway-system
spec:
  logging:
    level: "trace"
  service:
    spec:
      type: ClusterIP
  rawConfig:
    config:
      adminAddr: "0.0.0.0:15000"
  deployment:
    spec:
      template:
        metadata:
          labels:
            environment: development

