apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability
  namespace: jobmatch-prod
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.scout.local
      http:
        paths:
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-prometheus
                port:
                  number: 9090
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
