apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: observability
  values:
    grafana:
      enabled: true
      persistence:
        enabled: true
        type: pvc
        accessModes:
          - ReadWriteOnce
        size: 2Gi
      grafana.ini:
        server:
          domain: grafana.scout.local
          root_url: http://grafana.scout.local
        live:
          allowed_origins: http://grafana.scout.local
      service:
        type: ClusterIP
      sidecar:
        datasources:
          enabled: true
          defaultDatasourceScrapeFromSidecar: false 

      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-stack.observability.svc.cluster.local:3100
          jsonData:
            maxLines: 1000
          isDefault: false

    prometheus:
      enabled: true
      prometheusSpec:
        routePrefix: /prometheus
        externalUrl: http://grafana.scout.local/prometheus/
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector: {}
      service:
        type: ClusterIP