apiVersion: v1
kind: Service
metadata:
  name: agentgateway-gui
  namespace: agentgateway-system
spec:
  selector:
    app.kubernetes.io/name: agentgateway-external
  ports:
    - name: http
      port: 15000
      targetPort: 15000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentgateway-gui
  namespace: agentgateway-system
spec:
  ingressClassName: traefik
  rules:
    - host: agentgw.scout.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agentgateway-gui
                port:
                  number: 15000
    - host: job.scout.local
      http:
        paths:
          - path: /ui
            pathType: Prefix
            backend:
              service:
                name: agentgateway-gui
                port:
                  number: 15000

